---
title: "Metagenome Function"
author: "Ryan Waln"
format: html
editor: visual
---
## Introduction

This file serves as a full set of notes on the commands used for workshop 4 for Module 3 in MB5370 in order to assemble a meta genome of BBD using a smaller subset of genomic data taken from a previous PhD project 

The following steps are taken to assemble the meta genome:
- Assembly w/flye
- Binning w/metabat
- Bin quality check w/checkm
- Selecting bins based on checkm results
- Taxonomic classification w/gtdbtk
- Finding and annotating genes w/prokka
- Inferring metabolic pathways w/minpath

(Notes have # headings, code is in normal text format. Processing log is better formatted from learning about non-functioning bash chunks)

## Assembly with flye
### Create a directory called flye and make a symbolic link to bbd read data 
ln -s /pvol/data/metagenome_assembly/bbd_0.1.fastq.gz .

### Create A shell script named run_flye_bbd.sh in flye directory w/provided code then submit the job to slurm 
sbatch run_flye_bbd.sh
tail -f slurm-494.out

## Binning with metabat
### Move to top level directory and make a metabat diectory then extract depth information 
cat ../flye/bbd/assembly_info.txt  | grep -v '#' | awk '{OFS="\t";print $1,$3}' > depths_bbd.txt

### Reorder contigs based on depth 
cat depths_bbd.txt | awk '{print $1}' | xargs samtools faidx ../flye/bbd/assembly.fasta > assembly_bbd_ordered.fasta

### Run metabat 
metabat2 -i assembly_bbd_ordered.fasta -a depths_bbd.txt --cvExt -o bins_bbd/metabat --seed 5

## Check bin quality with checkm
###  Move to top level directory and make a checkm diectory
### Display lengths of all contigs from shortest to longest
cat ../flye/bbd/assembly.fasta | bioawk -c fastx '{print length($seq),$name}' | sort -n

### Run below code on longest contig 
mkdir bins_bbd
cp ../metabat/bins_bbd/*.fa bins_bbd/
samtools faidx ../flye/bbd/assembly.fasta contig_118 > bins_bbd/contig_118.fa

### Create A shell script named run_checkm_bbd.sh in the checkm directory w/provided code then submit the job to slurm 
sbatch run_checkm_bbd.sh
tail -f slurm-529.out

### Now that we have the bin data our goal is to answer: 
### What taxonomic groups of microbes are present in the BBD community and what can they do? 
### (what genes do they have and what biochemical pathways do these support?)


## Select Bins based on checkm results with gtdbtk 
### Go to checkm directory and look at results
### (markers are genes present once in the genome, marker sets, numbers represent count of genes found x times in genome)
head -n 20 checkm_results_bbd.txt 

### Use awk to bring up bins with a completeness greater than 15% to look at best assembled members of BBD community
cat checkm_results_bbd.txt | awk '$13>15'

### Print the bin ID of the members above and send them to an output file 
cat checkm_results_bbd.txt | awk '$13>15{print $1}'
cat checkm_results_bbd.txt | awk '$13>15{print $1}' > bbd_topbins.txt

## Perform taxonomic classification with gtdbtk
### Create a gtdbtk directory in the top level and then create a subfolder in the new directory called genomes 
### Copy each of the top bins identified earlier into the genomes folder as input for slurm to taxonomically classify each

while read bin;do echo $bin;done < ../checkm/bbd_topbins.txt
while read bin;do echo "../metabat/bins_bbd/${bin}.fa";done < ../checkm/bbd_topbins.txt
while read bin;do cp "../metabat/bins_bbd/${bin}.fa" genomes;done < ../checkm/bbd_topbins.txt

### Create A shell script named run_gtdbtk.sh in the gtdbtk directory w/provided code then submit the job to slurm
sbatch run_gtdbtk.sh
tail -f slurm-568.out

## Find and annotate genes with prokka

### The ultimate goal is to use the BBD metagenome to improve our understanding of metabolic processes within the mat.
### Thus we must identify the genes present within the genomes of bbd taxa.
### Prokka is a great program to identify gene sequences and identify homologous genes with known functions. 
### General idea it that if two genes share a common ancestor (ie are homologous) their functions are likely to be similar. 

###  Move to top level directory and make a prokka diectory and then find out the first bin ID in your lis
head -n 1 ../checkm/bbd_topbins.txt

### Run this bin ID as a test before submiting all bins to to slurm and display results to ensure there are no errors
bin=metabat.5
prokka --outdir $bin --prefix $bin  ../metabat/bins_bbd/${bin}.fa
ls metabat.5

### Create A shell script named run_prokka.sh in the prokka directory w/provided code then submit the job to slurm
sbatch run_prokka.sh
tail -f slurm-576.out

## Infer metabolic pathways with minpath
### Will use minpath to take functional info for individual genes and use this to infer the presence of broader biological pathways. 
### Will run this on each of the genomes (bins), minpath will then look at all of the annotated genes in our data and infer the minimal set of biological pathways that can explain the presence of all these genes

### Move to top level directory and make a minpath diectory 
### Inputs for minpath will be prepared for each bin based on the prokka .tsv file. Look at the .tsv file for a single bin (should show 9 genes)
head ../prokka/metabat.5/metabat.5.tsv

### Transform the tsv using awk so that only the unique ID for each gene (column 1) and its EC number (column 5) are kept 
head ../prokka/metabat.5/metabat.5.tsv | awk -F '\t' '{print $1,$5}'

### Ensure the output is tab separated and remove the header line
head ../prokka/metabat.5/metabat.5.tsv | awk -F '\t' '$5{OFS="\t";print $1,$5}' | grep -v '^locus'

### Change head to cat to include all genes
cat ../prokka/metabat.5/metabat.5.tsv | awk -F '\t' '$5{OFS="\t";print $1,$5}' | grep -v '^locus'

### Send above code to an output file so that it can be used as input to minpath
cat ../prokka/metabat.5/metabat.5.tsv | awk -F '\t' '$5{OFS="\t";print $1,$5}' | grep -v '^locus' > metabat.5.ec

### Run minpath on the file 
minpath -ec metabat.5.ec -report metabat.5.ec.report -details metabat.5.ec.details

### Look at the first few lines of output
head metabat.5.ec.report 

### Once Prokka is finished run the following code to prepare minpath inputs for all bins 
while read bin;do 
  cat ../prokka/$bin/${bin}.tsv | awk -F '\t' '$5{printf("%s\t%s\n", $1,$5)}' | grep -v '^locus' > ${bin}.ec 
done < ../checkm/bbd_topbins.txt

### Run minpath on every bin
while read bin;do 
  minpath -ec ${bin}.ec -report ${bin}.ec.report -details ${bin}.ec.details
done < ../checkm/bbd_topbins.txt

### Minpath should prodce a lot of output, but we are only intrested in 2 pathways 

### The first pathway is named photosynthesis light reactions (metacyc code: PWY-101) 
### This pathway includes the essential components of photosynthesis that occur in light, Photosystem I and Photosystem II

### The second pathway is called superpathway of tetrathionate reduction (metacyc code: PWY-5360) 
### This pathway is important because it includes enzymes required to reduce sulfite to hydrogen sulfide

### Search for photosynthesis light reactions across all bins
grep 'PWY-101' *.ec.report

### List of bins with pathway:
metabat.12
metabat.34
metabat.40 
metabat.51

### Cross reference results with the output from gtdbtk to see the taxonomy of bins containing this pathway 
grep 'metabat.12' ../gtdbtk/out/gtdbtk.bac120.summary.tsv

### Search for superpathway of tetrathionate reduction across all bins
grep 'PWY-5360' *.ec.report

### List of bins with pathway:
metabat.70

### Cross reference results with the output from gtdbtk to see the taxonomy of bins containing this pathway 
grep 'metabat.70' ../gtdbtk/out/gtdbtk.bac120.summary.tsv

### Read taxonomic results of bins with pathways
```{r}
library(tidyverse)
Taxa_results <- read_tsv("gtdbtk/out/gtdbtk.bac120.summary.tsv")
Taxa_results
```

### To find number of genes prokka assigned an ec number run below code in prokka directory:
cat ../minpath/*.ec|wc -l

